// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvKUJ1gKRmQsWhOEyBeN45I0wTk4C21M',
    appId: '1:341113239686:web:b000d09811e435669ef907',
    messagingSenderId: '341113239686',
    projectId: 'rent-flow-ccjjwn',
    authDomain: 'rent-flow-ccjjwn.firebaseapp.com',
    storageBucket: 'rent-flow-ccjjwn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrC1AfYm4KxdY_vR4KXifXmmpicQreIBY',
    appId: '1:341113239686:android:d0464c4110af469e9ef907',
    messagingSenderId: '341113239686',
    projectId: 'rent-flow-ccjjwn',
    storageBucket: 'rent-flow-ccjjwn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCEVfF9FbvoNDY_a4hl453tIqaI1-Jf4',
    appId: '1:341113239686:ios:5e5c898b498e9ad89ef907',
    messagingSenderId: '341113239686',
    projectId: 'rent-flow-ccjjwn',
    storageBucket: 'rent-flow-ccjjwn.appspot.com',
    iosBundleId: 'com.example.rentoflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxCEVfF9FbvoNDY_a4hl453tIqaI1-Jf4',
    appId: '1:341113239686:ios:5e5c898b498e9ad89ef907',
    messagingSenderId: '341113239686',
    projectId: 'rent-flow-ccjjwn',
    storageBucket: 'rent-flow-ccjjwn.appspot.com',
    iosBundleId: 'com.example.rentoflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCimU4FPzQ0Ay14Z6cD8VBlXuM05mVWFkM',
    appId: '1:341113239686:web:4e38f3721e0f538a9ef907',
    messagingSenderId: '341113239686',
    projectId: 'rent-flow-ccjjwn',
    authDomain: 'rent-flow-ccjjwn.firebaseapp.com',
    storageBucket: 'rent-flow-ccjjwn.appspot.com',
  );
}
